# Generated by Django 6.0.4 on 2026-05-23 07:42

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productattribute_product_discount_price_and_more'),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
    ]
